import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import HeaderDesktop from "./HeaderDesktop";
import HeaderMobile from "./HeaderMobile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
          rel="stylesheet"
        />
      </head>
      <body
        className={`overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className="w-full bg-[#F6F7F9] h-screen overflow-hidden flex flex-col">
            <div className="hidden md:block">
              <HeaderDesktop />
            </div>
            <div className="block md:hidden">
              <HeaderMobile />
            </div>
            {children}
            {modal}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
